apiVersion: v1
kind: Service
metadata:
  namespace: aiops
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 32002
  selector:
    app: kibana
