apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: aiops
  name: elasticsearch-pvc
  labels:
    component: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
